import { ArtworkCategory } from './types';
import type { Artwork } from './types';

export const ARTWORKS: Artwork[] = [
  {
    id: 1,
    title: 'Woven Earth',
    year: 2024,
    category: ArtworkCategory.HANDMADE,
    medium: 'Handmade-paper collage',
    size: '24x36 inches',
    price: 2800,
    imageUrl: 'https://i.pinimg.com/1200x/09/bc/a8/09bca8777a1ce9c80900a578a7418cb4.jpg',
    description: 'A tactile exploration of natural forms, created with layered, handmade paper and organic pigments. The piece evokes a sense of geological time and texture.',
  },
  {
    id: 2,
    title: 'Vector Bloom',
    year: 2024,
    category: ArtworkCategory.DIGITAL,
    medium: 'Digital Illustration',
    size: '∞',
    price: 1500,
    imageUrl: 'https://i.pinimg.com/1200x/a8/62/fb/a862fba49827af4c47a084caf6a7b636.jpg',
    description: 'A vibrant digital illustration capturing the explosive energy of a flower in bloom, rendered with clean lines and a bold, graphic palette.',
  },
  {
    id: 3,
    title: 'Fossil Record',
    year: 2023,
    category: ArtworkCategory.HANDMADE,
    medium: 'Pressed botanicals on cotton paper',
    size: '18x24 inches',
    price: 1950,
    imageUrl: 'https://i.pinimg.com/1200x/57/f4/46/57f44617f763847f3d665cd443cd32ae.jpg',
    description: 'A delicate arrangement of pressed local flora, preserving a moment in time and celebrating the beauty of decay and preservation.',
  },
  {
    id: 4,
    title: 'Circuit Garden',
    year: 2024,
    category: ArtworkCategory.DIGITAL,
    medium: '3D Render, Blender',
    size: '4000x4000px',
    price: 2200,
    imageUrl: 'https://i.pinimg.com/736x/4a/e2/34/4ae234da4881a16dc0281e0fab465d0e.jpg',
    description: 'A surreal landscape where nature and technology intertwine. Bioluminescent plants grow on a substrate of glowing circuit boards.',
  },
  {
    id: 5,
    title: 'Tidal Flow',
    year: 2023,
    category: ArtworkCategory.DIGITAL,
    medium: 'Algorithmic Art, p5.js',
    size: '∞',
    price: 1800,
    imageUrl: 'https://i.pinimg.com/736x/9b/96/40/9b9640245d13f7daef3d95ef00ed7bc7.jpg',
    description: 'A generative piece that visualizes the push and pull of ocean tides, creating intricate, ever-changing patterns of light and color.',
  },
  {
    id: 6,
    title: 'Sun-Bleached',
    year: 2022,
    category: ArtworkCategory.HANDMADE,
    medium: 'Mixed media on wood panel',
    size: '30x30 inches',
    price: 2500,
    imageUrl: 'https://i.pinimg.com/1200x/61/f1/77/61f177b375fd6c6a94b5bc5615bc568d.jpg',
    description: 'Utilizes sun-bleached fabric, sand, and acrylics to capture the harsh, beautiful light of a desert landscape.',
  },
  {
    id: 11,
    title: "Cosmic Ritual",
    year: 2024,
    category: ArtworkCategory.DIGITAL,
    medium: "Digital Painting",
    size: "∞",
    imageUrl: "https://i.pinimg.com/736x/60/b0/a5/60b0a5e96066fb9ea27db52c74850d0c.jpg",
    description: "An abstract representation of cosmic energies converging, created with a dynamic brushwork style to convey motion and power.",
  },
  {
    id: 12,
    title: "Neon Depths",
    year: 2024,
    category: ArtworkCategory.DIGITAL,
    medium: "3D Render",
    size: "4000x5000px",
    imageUrl: "https://i.pinimg.com/736x/9c/b1/90/9cb19058d1165283082cc9230a69b02a.jpg",
    description: "A surreal journey into a vibrant, glowing underwater world, exploring themes of light, life, and the unknown in the deep.",
  },
  {
    id: 13,
    title: "Woven Silence",
    year: 2023,
    category: ArtworkCategory.HANDMADE,
    medium: "Handmade-paper collage",
    size: "20x30 inches",
    imageUrl: "https://i.pinimg.com/736x/6e/c0/55/6ec0556f9cda3d8abc6fbefeaa65a292.jpg",
    description: "Layers of textured, handmade paper are woven together to create a contemplative piece that explores silence and space through material.",
  },
  {
    id: 14,
    title: "Terracotta Layers",
    year: 2024,
    category: ArtworkCategory.HANDMADE,
    medium: "Layered paper and pigment",
    size: "24x24 inches",
    imageUrl: "https://i.pinimg.com/736x/d2/7e/2a/d27e2a9105dfef95cccc5757085bdde5.jpg",
    description: "Inspired by arid landscapes, this piece uses earthy pigments and layered torn paper to build a rich, topographical surface.",
  }
];

export const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/hunny.exe?igsh=MW01ZGNrNmcwMjVqcA==',
  twitter: 'https://x.com/boybeast76?t=GZLu8SJ-Kj4-HOmASAWsUQ&s=09',
  linkedin: 'https://www.linkedin.com/in/hashant-bhati-6454b2381?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
};